### ISSUE TITLE
Need to change websites scraped

### ISSUE THREAD

**Issue by aadiltajani** [aadiltajani/slash#1]
Current implementation is using only amazon, target and walmart to scrape and show products and we need to change it to get products from many other available websites

**Comment by aadiltajani** [comment]
Proposed solution 1: We can scrape Google instead of 3 files as it is showing products from as many websites available.

Any other ideas or views on this? @KaustubhKael @ArpitCh21 @Dhruvish-Patel ?

**Comment by KaustubhKael** [comment]
yes, seems like we can reduce wait times by waiting for one single end point instead of three

**Comment by ArpitCh21** [comment]
yes, it's a good idea to scrape google. It'll give more results than just scraping 3 files.

**Comment by aadiltajani** [comment]
Seems we are getting good results
