### ISSUE TITLE
Need to redirect users to original website

### ISSUE THREAD

**Issue by ArpitCh21** [aadiltajani/slash#6]
We need to redirect users to the original websites when they click on a product.

**Comment by Dhruvish-Patel** [comment]
Added a buy now button to the product where the user will be redirected to the original website where they can but the actual products.





![ezgif-2-ff63f87844](https://user-images.githubusercontent.com/53443266/205455755-317e49b0-3987-48f0-adb8-1abeb313325e.gif)
